name: "Setup Releaser"
description: "Common Actions to Set up Releaser"
runs:
  using: "composite"
  steps:
    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@tmp
    - name: Install Dependencies
      shell: bash
      run: |
        pip install -e .
